/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <iostream>
#include <limits>

using namespace std;

long long get();

int main(void)
{
	long long result = get();
	if (result == -1) {
		cout << "Number to big for long long" << endl;
	} else {
		cout << result << endl;
	}

	return 0;
}

long long get()
{
	long long counter;
	unsigned int next_num = 1;
	
	for (unsigned long long i = 1; i < numeric_limits<unsigned long long>::max(); i += ++next_num) {
		counter = 0;
		
		for (unsigned long long j = 1; j <= i; ++j) {
			if (!(i % j)) {
				++counter;
			}
		}
		
		if (counter > 500)
			return i;
	}
	
	return -1;
}
