/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;


int main(void)
{
	unsigned int prev[] = {1, 2};
	unsigned int result = 2;
	
	for (unsigned int i = 0; i < 4000000;) {
		i = prev[0] + prev[1];
		
		if (!(i & 1)) {
			result += i;
		}
		
		prev[0] = prev[1];
		prev[1] = i;
	}
	
	cout << "Sum of even valued terms in the Fibonacci sequence below 4,000,000 is " << result << '.' << endl;
	
	return 0;
}
